[colors]
ansi = [
    '000000',
    'FF0800', # git deleted line & git unstaged
    '7CFC00', # git added line
    'D020FF', # quote or double quote (string)
    '00BFFF', # when ll, time & icon color
    '7CFC00', # g a background
    'FF8200', # command option
    'FF0800',
]

# background = '000000'

brights = [
    '7CFC00', # recommand (auto complete)
    'FC102F', # already typed
    'E0F7FA',
    'FF8200', # ll -> group id, user id
    'E0F7FA', # ll -> file, folder name
    'E0F7FA',
    'FFFFFF', # special symbol
    'E0F7FA',
]

cursor_bg = '7CFC00'
cursor_border = '7CFC00'
cursor_fg = '000000'
foreground = '87CEFA'
selection_bg = '85B09A'
selection_fg = 'FFA0A0'

[colors.indexed]

[metadata]
author = 'peco (https://github.com/treetea-bro)'
name = 'PecoArcade'
